DROP DATABASE IF EXISTS [06_MEDICINE_STORE_DB]
CREATE DATABASE [06_MEDICINE_STORE_DB]
ON
(
	NAME = 'MEDICINE_STORE_DB',
	FILENAME = 'C:\00_DATA\04_DE_CODE\LESSON_04\MEDICINE_STORE_DB.mdf',
	SIZE = 10MB,
	MAXSIZE = 100MB,
	FILEGROWTH = 5MB)
LOG ON
(
	NAME = 'MEDICINE_STORE_DB_LOG',
	FILENAME = 'C:\00_DATA\04_DE_CODE\LESSON_04\MEDICINE_STORE_DB.ldf',
	SIZE = 5MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 5MB
)

USE [06_MEDICINE_STORE_DB]
GO

-- CREATE SCHEMAS
CREATE SCHEMA People;
GO

CREATE SCHEMA Medicine;
GO

CREATE SCHEMA Bill;
GO

DROP TABLE IF EXISTS People.Customer
CREATE TABLE People.Customer
(
	CustomerId VARCHAR(50) NOT NULL PRIMARY KEY,
	CustomerName VARCHAR(100) NOT NULL,
	CustomerPhone VARCHAR(10) NOT NULL CONSTRAINT CK_CustomePhone CHECK(LEN(CustomerPhone) = 10 AND CustomerPhone NOT LIKE '%[^0-9]%')
)

DROP TABLE IF EXISTS People.Staff
CREATE TABLE People.Staff
(
	StaffId VARCHAR(50) NOT NULL PRIMARY KEY,
	IdentityCardNumber VARCHAR(12) NOT NULL CONSTRAINT CK_StaffIdentityCardNumber CHECK(LEN(IdentityCardNumber) = 12 AND IdentityCardNumber LIKE '%[^0-9]%'),
	FullName NVARCHAR(100) NOT NULL,
	StaffAddress NVARCHAR(100) NOT NULL,
	Phone VARCHAR(10) NOT NULL CONSTRAINT CK_StaffPhone CHECK(LEN(Phone) = 10 AND Phone NOT LIKE '%[^0-9]%')
)

DROP TABLE IF EXISTS Bill.Invoice
CREATE TABLE Bill.Invoice
(
	InvoiceId VARCHAR(10) NOT NULL PRIMARY KEY,
	SaleDate DATE NOT NULL,
	CustomerId VARCHAR(50) NOT NULL,
	StaffId VARCHAR(50) NOT NULL,
	--CONSTRAINT UQ_Invoice_CustomerAndStaff UNIQUE(CustomerId, StaffId),
	CONSTRAINT FK_Invoice_Customer FOREIGN KEY (CustomerId) REFERENCES People.Customer(CustomerId) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_Invoice_Staff FOREIGN KEY (StaffId) REFERENCES People.Staff(StaffId) ON DELETE CASCADE ON UPDATE CASCADE
)

DROP TABLE IF EXISTS Medicine.Medicine
CREATE TABLE Medicine.Medicine
(
	MedicineId VARCHAR(10) NOT NULL PRIMARY KEY,
	NameMedicine VARCHAR(100) NOT NULL,
	FunctionMedicine VARCHAR(500) NOT NULL,
	CreateDate DATE NOT NULL,
	ExpiredDate DATE NOT NULL
)

DROP TABLE IF EXISTS Bill.InvoiceMedicine
CREATE TABLE Bill.InvoiceMedicine
(
	InvoiceMedicineId VARCHAR(10) NOT NULL PRIMARY KEY,
	MedicineId VARCHAR(10) NOT NULL,
	Quantity INT NOT NULL CONSTRAINT CK_InvoiceMedicine_Quantity CHECK(Quantity > 0),
	CONSTRAINT FK_InvoiceMedicine_Medicine FOREIGN KEY (MedicineId) REFERENCES  Medicine.Medicine(MedicineId) ON DELETE CASCADE ON UPDATE CASCADE
)

